project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  title: "AndrewsLab Handbook"
  author: "Shea J Andrews"
  date: "2023-07-26"
  repo-url: https://github.com/AndrewsLabUCSF/Lab-Handbook
  sharing: [twitter]
  chapters:
    - part: index.qmd
      chapters: 
        - scripts/about.qmd
    - part: scripts/policies.qmd
      chapters:
        - scripts/getting_started.qmd
        - scripts/working.qmd
        - scripts/communication.qmd
        - scripts/expectations.qmd
        - scripts/setbacks.qmd
        - scripts/open_science.qmd 
        - scripts/rcr.qmd 
    - part: scripts/resources.qmd
      chapters:
        - scripts/compute.qmd
        - scripts/labscrum.qmd
        - scripts/sap.qmd
        - scripts/directories.qmd
        - scripts/grants.qmd
        - scripts/journal_club.qmd
        - scripts/reading_lists.qmd
    - part: scripts/conclusion.qmd
      chapters:
        - scripts/signatures.qmd
        - scripts/acknowledgments.qmd
 
format:
  html:
    theme: yeti
    number-depth: 1


editor: visual
