---
title: Reading List
---

This curated list of references is an essential part of our shared knowledge base, designed to provide you with a solid foundation and a deeper understanding of the fields we are passionate about: genetic epidemiology and neurodegenerative disease. You will also find readings on other aspects of the scientific enterprise such as writing, presentations, and career development.

The references included here have been carefully selected for their relevance, clarity, and contribution to our field. They range from seminal papers that have shaped our understanding of genetic epidemiology and neurodegenerative disease, to the latest cutting-edge research that pushes the boundaries of what we know. You will also find comprehensive textbooks, insightful reviews, and practical guides that cover the methodologies, tools, and techniques we use in our lab.

Whether you are a new member seeking to familiarize yourself with our field, or an experienced researcher looking to stay abreast of the latest developments, this reading list is a valuable resource. We encourage you to delve into these materials and explore the fascinating world of genetic epidemiology and neurodegenerative disease.

Remember, learning is a lifelong journey, and science is continually evolving. This reading list is not static but will be updated periodically to reflect new discoveries and advancements in our field. We also welcome your suggestions for additions to the list, as we believe that everyone in our lab can contribute to our collective learning.


## Alzheimer's disease 
### What is AD 
- Knopman, D. S. et al. Alzheimer disease. Nat Rev Dis Primers 7, 33 (2021).
- Alzheimer's Association. 2023 Alzheimer’s disease facts and figures. Alzheimer’s Dementia (2023) doi:10.1002/alz.13016.
- Sirkis, D. W., et al. Dissecting the clinical heterogeneity of early-onset Alzheimer’s disease. Mol Psychiatr 27, 2674–2688 (2022).
- Frisoni, G. B. et al. The probabilistic model of Alzheimer disease: the amyloid hypothesis revised. Nat Rev Neurosci 23, 53–66 (2022).

### Health Disparities   
- Kornblith, E. et al. Association of Race and Ethnicity With Incidence of Dementia Among Older Adults. Jama 327, 1488–1495 (2022).
- Adkins‐Jackson, P. B. et al. The structural and social determinants of Alzheimer’s disease related dementias. Alzheimer’s Dementia (2023) doi:10.1002/alz.13027.
    

### Genetics of AD
- Andrews, S. J. et al. The complex genetic architecture of Alzheimer’s disease: novel insights and future directions. eBioMedicine 90, 104511 (2023).
- Reitz, C., Pericak-Vance, M. A., Foroud, T. & Mayeux, R. A global view of the genetic basis of Alzheimer disease. Nat Rev Neurol 1–17 (2023) doi:10.1038/s41582-023-00789-z.
- Lambert, J.-C., Ramirez, A., Grenier-Boley, B. & Bellenguez, C. Step by step: towards a better understanding of the genetic architecture of Alzheimer’s disease. Mol Psychiatr 1–12 (2023) doi:10.1038/s41380-023-02076-1.
- Andrews, S. J., Fulton-Howard, B. & Goate, A. Interpretation of risk loci from genome-wide association studies of Alzheimer’s disease. Lancet Neurology 19, 326–335 (2020).
- Bellenguez, C. et al. New insights into the genetic etiology of Alzheimer’s disease and related dementias. Nat Genet 54, 412–436 (2022).

- [Alzheimer's Disease Genetics Global Symposium](https://alz-genetics.niagads.org/). Webinar series with 40+ presentations and a Q&A discussion from global experts in the field of AD genetics.

### Risk factors 
- Livingston, G. et al. Dementia prevention, intervention, and care: 2020 report of the Lancet Commission. Lancet 396, 413–446 (2020).
- Nianogo, R. A. et al. Risk Factors Associated With Alzheimer Disease and Related Dementias by Sex and Race and Ethnicity in the US. Jama Neurol 79, 584–591 (2022).
  

### Dementia risk scores  
- Anstey, K. J. et al. Dementia Risk Scores and Their Role in the Implementation of Risk Reduction Guidelines. Front Neurol 12, 765454 (2022).
- Huque, M. H. et al. CogDrisk, ANU-ADRI, CAIDE, and LIBRA Risk Scores for Estimating Dementia Risk. JAMA Netw. Open 6, e2331460 (2023).
- Walsh, S. et al. What would a population‐level approach to dementia risk reduction look like, and how would it work? Alzheimer’s Dement. 19, 3203–3209 (2023).

## Genetic Epidemiology
- [Psychiatric Genomics Consortium Online Textbook](https://youtube.com/playlist?list=PLTQnXmu3Zkmo8209LHBw4SDHqbQaF2NGX&si=gFPDz1OkjZCPSfNo): YouTube series from the PGC highlighting different methods and tools used in genetic epidemiology.  

### Genome-wide association studies 
- Uffelmann, E. et al. Genome-wide association studies. Nat Rev Methods Primers 1, 59 (2021).
- Marees, A. T. et al. A tutorial on conducting genome‐wide association studies: Quality control and statistical analysis. Int J Method Psych 27, e1608 (2018).
- Balagué-Dobón, L., Cáceres, A. & González, J. R. Fully exploiting SNP arrays: a systematic review on the tools to extract underlying genomic structure. Brief Bioinform 23, bbac043 (2022).
- Abdellaoui, A., Yengo, L., Verweij, K. J. H. & Visscher, P. M. 15 years of GWAS discovery: Realizing the promise. Am J Hum Genetics (2023) doi:10.1016/j.ajhg.2022.12.011.  
- Brandes, N., Weissbrod, O. & Linial, M. Open problems in human trait genetics. Genome Biol 23, 131 (2022).
  

### Polygenic risk scores 
- Choi, S. W., Mak, T. S.-H. & O’Reilly, P. F. Tutorial: a guide to performing polygenic risk score analyses. Nat Protoc 15, 2759–2772 (2020).
- Kachuri, L. et al. Principles and methods for transferring polygenic risk scores across global populations. Nat. Rev. Genet. 1–18 (2023) doi:10.1038/s41576-023-00637-2.
- Ding, Y. et al. Polygenic scoring accuracy varies across the genetic ancestry continuum. Nature 1–8 (2023) doi:10.1038/s41586-023-06079-4.
- Moorthie et al. Evaluation of polygenic score applications. [PHG Foundation (2023)](https://www.phgfoundation.org/report/evaluation-of-polygenic-score-applications)

### Mendelian randomization 
- Sanderson, E. et al. Mendelian randomization. Nat Rev Methods Primers 2, 6 (2022).
- Davies, N. M., Holmes, M. V. & Smith, G. D. Reading Mendelian randomisation studies: a guide, glossary, and checklist for clinicians. Bmj 362, k601 (2017).
- Hemani, G. et al. The MR-Base platform supports systematic causal inference across the human phenome. Elife 7, e34408 (2018).
    
### Genetic correlations 
- Rheenen, W. van, Peyrot, W. J., Schork, A. J., Lee, S. H. & Wray, N. R. Genetic correlations of polygenic disease traits: from theory to practice. Nat Rev Genetics 20, 567–581 (2019).

### Heritability 
- Barry, C.-J. S. et al. How to estimate heritability: a guide for genetic epidemiologists. Int J Epidemiol (2022) doi:10.1093/ije/dyac224.
  
### Genetic ancestry 
- National Academies of Sciences, Engineering, and Medicine. 2023. Using Population Descriptors in Genetics and Genomics Research: A New Framework for an Evolving Field. Washington, DC: The National Academies Press. https://doi.org/10.17226/26902.
- Lewis, A. C. F. et al. Getting genetic ancestry right for science and society. Science 376, 250–252 (2022).
- Rebbeck, T. R., Mahal, B., Maxwell, K. N., Garraway, I. P. & Yamoah, K. The distinct impacts of race and genetic ancestry on health. Nat Med 28, 890–893 (2022).
- Fatumo, S. et al. A roadmap to increase diversity in genomic studies. Nat Med 28, 243–250 (2022).
      

## Bioinformatics 
### Reproducibility 
- Rodrigues, Bruno. Building reproducible analytical pipelines with R. 2023
- Mölder, F. et al. Sustainable data analysis with Snakemake. F1000research 10, 33 (2021).
- Ziemann, Poulain, and Bora. The five pillars of computational reproducibility: Bioinformatics and beyond. [OSF (2023)](https://osf.io/4pd9n/)

## Writing & communication
### How to write a paper 
- Mensh, B. & Kording, K. Ten simple rules for structuring papers. [PLoS Comput. Biol. 13, e1005619 (2017)](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005619)    
- Zhang, W. Ten Simple Rules for Writing Research Papers. [PLoS Comput. Biol. 10, e1003453 (2014)](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003453)
- Ecarnot, F., Seronde, M.-F., Chopard, R., Schiele, F. & Meneveau, N. Writing a scientific article: A step-by-step guide for beginners. [Eur. Geriatr. Med. 6, 573–579 (2015)](https://doi.org/10.1016/j.eurger.2015.08.005)
  